Improved bash and perl scripts

diff --git a/cronytdl b/cronytdl
--- a/cronytdl
+++ b/cronytdl
@@ -3,35 +3,35 @@
 #Channel name
 channelname1=Insert channel name here
 channelid1=Insert channel id here
-cd ~/Videos/$channelname1/
-yt-dlp -f bestvideo+bestaudio --download-archive ~/Videos/$channelname1/.$channelname1 --merge-output-format mkv https://www.youtube.com/channel/$channelid1 || $(
-curl https://www.youtube.com/feeds/videos.xml?channel_id=$channelid1 | grep yt:videoId | sed -e 's/<\/*yt:videoId>//g' -e 's/ //g' > .ids.txt
-find * | sed 's/....$//g' | grep -o '.\{11\}$' > .local.txt
+cd ~/Videos/"$channelname1"/ || { echo "Failure"; exit 1; }
+yt-dlp -f bestvideo+bestaudio --download-archive ~/Videos/"$channelname1"/."$channelname1" --merge-output-format mkv https://www.youtube.com/channel/"$channelid1" || $(
+curl https://www.youtube.com/feeds/videos.xml?channel_id="$channelid1" | grep yt:videoId | sed -e 's/<\/*yt:videoId>//g' -e 's/ //g' > .ids.txt
+find ./* | sed 's/....$//g' | grep -o '.\{11\}$' > .local.txt
 missing=$(comm -23 <(sort .ids.txt) <(sort .local.txt))
 for dlvideo in $missing; do
-	ytdl -a -o audio $dlvideo
-	ytdl -b -o video $dlvideo
+	ytdl -a -o audio "$dlvideo"
+	ytdl -b -o video "$dlvideo"
 	ffmpeg -i video.mp4 -i audio.mp4 -c:v copy -c:a copy output.mp4
-	title=$(yt-dlp -e $dlvideo | sed -e 's/ /_/g' -e 's/\///g')
-	mv output.mp4 $title-$dlvideo.mp4
+	title=$(yt-dlp -e "$dlvideo" | sed -e 's/ /_/g' -e 's/\///g')
+	mv output.mp4 "$title"-"$dlvideo".mp4
 	rm video.mp4 && rm audio.mp4
-	echo "youtube $dlvideo" >> .$channelname1
+	echo youtube "$dlvideo" >> ."$channelname1"
 done
 rm .ids.txt && rm .local.txt)
 
 channelid2=Insert channel id here
-yt-dlp -f bestvideo+bestaudio --download-archive ~/Videos/$channelname1/.$channelname1 --merge-output-format mkv https://www.youtube.com/channel/$channelid2 || $(
-curl https://www.youtube.com/feeds/videos.xml?channel_id=$channelid2 | grep yt:videoId | sed -e 's/<\/*yt:videoId>//g' -e 's/ //g' > .ids.txt
-find * | sed 's/....$//g' | grep -o '.\{11\}$' > .local.txt
+yt-dlp -f bestvideo+bestaudio --download-archive ~/Videos/"$channelname1"/."$channelname1" --merge-output-format mkv https://www.youtube.com/channel/"$channelid2" || $(
+curl https://www.youtube.com/feeds/videos.xml?channel_id="$channelid2" | grep yt:videoId | sed -e 's/<\/*yt:videoId>//g' -e 's/ //g' > .ids.txt
+find ./* | sed 's/....$//g' | grep -o '.\{11\}$' > .local.txt
 missing=$(comm -23 <(sort .ids.txt) <(sort .local.txt))
 for dlvideo in $missing; do
-	ytdl -a -o audio $dlvideo
-	ytdl -b -o video $dlvideo
+	ytdl -a -o audio "$dlvideo"
+	ytdl -b -o video "$dlvideo"
 	ffmpeg -i video.mp4 -i audio.mp4 -c:v copy -c:a copy output.mp4
-	title=$(yt-dlp -e $dlvideo | sed -e 's/ /_/g' -e 's/\///g')
-	mv output.mp4 $title-$dlvideo.mp4
+	title=$(yt-dlp -e "$dlvideo" | sed -e 's/ /_/g' -e 's/\///g')
+	mv output.mp4 "$title"-"$dlvideo".mp4
 	rm video.mp4 && rm audio.mp4
-	echo "youtube $dlvideo" >> .$channelname1
+	echo youtube "$dlvideo" >> ."$channelname1"
 done
 rm .ids.txt && rm .local.txt)
 
@@ -39,19 +39,19 @@ rm .ids.txt && rm .local.txt)
 #Channel name
 channelname2=Insert channel name here
 channelid3=Insert channel id here
-cd ~/Videos/$channelname2/
-yt-dlp -f bestvideo+bestaudio --download-archive ~/Videos/$channelname2/.$channelname2 --merge-output-format mkv https://www.youtube.com/channel/$channelid3 || $(
-curl https://www.youtube.com/feeds/videos.xml?channel_id=$channelid3 | grep yt:videoId | sed -e 's/<\/*yt:videoId>//g' -e 's/ //g' > .ids.txt
-find * | sed 's/....$//g' | grep -o '.\{11\}$' > .local.txt
+cd ~/Videos/"$channelname2"/ || { echo "Failure"; exit 1; }
+yt-dlp -f bestvideo+bestaudio --download-archive ~/Videos/"$channelname2"/."$channelname2" --merge-output-format mkv https://www.youtube.com/channel/"$channelid3" || $(
+curl https://www.youtube.com/feeds/videos.xml?channel_id="$channelid3" | grep yt:videoId | sed -e 's/<\/*yt:videoId>//g' -e 's/ //g' > .ids.txt
+find ./* | sed 's/....$//g' | grep -o '.\{11\}$' > .local.txt
 missing=$(comm -23 <(sort .ids.txt) <(sort .local.txt))
 for dlvideo in $missing; do
-	ytdl -a -o audio $dlvideo
-	ytdl -b -o video $dlvideo
+	ytdl -a -o audio "$dlvideo"
+	ytdl -b -o video "$dlvideo"
 	ffmpeg -i video.mp4 -i audio.mp4 -c:v copy -c:a copy output.mp4
-	title=$(yt-dlp -e $dlvideo | sed -e 's/ /_/g' -e 's/\///g')
-	mv output.mp4 $title-$dlvideo.mp4
+	title=$(yt-dlp -e "$dlvideo" | sed -e 's/ /_/g' -e 's/\///g')
+	mv output.mp4 "$title"-"$dlvideo".mp4
 	rm video.mp4 && rm audio.mp4
-	echo "youtube $dlvideo" >> .$channelname2
+	echo youtube "$dlvideo" >> ."$channelname2"
 done
 rm .ids.txt && rm .local.txt)
 
@@ -59,19 +59,19 @@ rm .ids.txt && rm .local.txt)
 #Channel name
 channelname3=Insert channel name here
 channelid4=Insert channel id here
-cd ~/Videos/$channelname3/
-yt-dlp -f bestvideo+bestaudio --download-archive ~/Videos/$channelname3/.$channelname3 --merge-output-format mkv https://www.youtube.com/channel/$channelid4 || $(
-curl https://www.youtube.com/feeds/videos.xml?channel_id=$channelid4 | grep yt:videoId | sed -e 's/<\/*yt:videoId>//g' -e 's/ //g' > .ids.txt
-find * | sed 's/....$//g' | grep -o '.\{11\}$' > .local.txt
+cd ~/Videos/"$channelname3"/ || { echo "Failure"; exit 1; }
+yt-dlp -f bestvideo+bestaudio --download-archive ~/Videos/"$channelname3"/."$channelname3" --merge-output-format mkv https://www.youtube.com/channel/"$channelid4" || $(
+curl https://www.youtube.com/feeds/videos.xml?channel_id="$channelid4" | grep yt:videoId | sed -e 's/<\/*yt:videoId>//g' -e 's/ //g' > .ids.txt
+find ./* | sed 's/....$//g' | grep -o '.\{11\}$' > .local.txt
 missing=$(comm -23 <(sort .ids.txt) <(sort .local.txt))
 for dlvideo in $missing; do
-	ytdl -a -o audio $dlvideo
-	ytdl -b -o video $dlvideo
+	ytdl -a -o audio "$dlvideo"
+	ytdl -b -o video "$dlvideo"
 	ffmpeg -i video.mp4 -i audio.mp4 -c:v copy -c:a copy output.mp4
-	title=$(yt-dlp -e $dlvideo | sed -e 's/ /_/g' -e 's/\///g')
-	mv output.mp4 $title-$dlvideo.mp4
+	title=$(yt-dlp -e "$dlvideo" | sed -e 's/ /_/g' -e 's/\///g')
+	mv output.mp4 "$title"-"$dlvideo".mp4
 	rm video.mp4 && rm audio.mp4
-	echo "youtube $dlvideo" >> .$channelname3
+	echo youtube "$dlvideo" >> ."$channelname3"
 done
 rm .ids.txt && rm .local.txt)
 
@@ -79,18 +79,18 @@ rm .ids.txt && rm .local.txt)
 #Channel name
 channelname4=Insert channel name here
 channelid5=Insert channel id here
-cd ~/Videos/$channelname4/
-yt-dlp -f bestvideo+bestaudio --download-archive ~/Videos/$channelname4/.$channelname4 --merge-output-format mkv https://www.youtube.com/channel/$channelid5 || $(
-curl https://www.youtube.com/feeds/videos.xml?channel_id=$channelid5 | grep yt:videoId | sed -e 's/<\/*yt:videoId>//g' -e 's/ //g' > .ids.txt
-find * | sed 's/....$//g' | grep -o '.\{11\}$' > .local.txt
+cd ~/Videos/"$channelname4"/ || { echo "Failure"; exit 1; }
+yt-dlp -f bestvideo+bestaudio --download-archive ~/Videos/"$channelname4"/."$channelname4" --merge-output-format mkv https://www.youtube.com/channel/"$channelid5" || $(
+curl https://www.youtube.com/feeds/videos.xml?channel_id="$channelid5" | grep yt:videoId | sed -e 's/<\/*yt:videoId>//g' -e 's/ //g' > .ids.txt
+find ./* | sed 's/....$//g' | grep -o '.\{11\}$' > .local.txt
 missing=$(comm -23 <(sort .ids.txt) <(sort .local.txt))
 for dlvideo in $missing; do
-	ytdl -a -o audio $dlvideo
-	ytdl -b -o video $dlvideo
+	ytdl -a -o audio "$dlvideo"
+	ytdl -b -o video "$dlvideo"
 	ffmpeg -i video.mp4 -i audio.mp4 -c:v copy -c:a copy output.mp4
-	title=$(yt-dlp -e $dlvideo | sed -e 's/ /_/g' -e 's/\///g')
-	mv output.mp4 $title-$dlvideo.mp4
+	title=$(yt-dlp -e "$dlvideo" | sed -e 's/ /_/g' -e 's/\///g')
+	mv output.mp4 "$title"-"$dlvideo".mp4
 	rm video.mp4 && rm audio.mp4
-	echo "youtube $dlvideo" >> .$channelname4
+	echo youtube "$dlvideo" >> ."$channelname4"
 done
 rm .ids.txt && rm .local.txt)
